### ISSUE TITLE
npm audit warning - path-to-regexp

### ISSUE THREAD

**Issue by apepper** [lwsjs/rewrite#15]
`npm audit` currently gives a warning for this package due to its dependencies.

Namely the `path-to-regexp` package creates this warning: https://github.com/advisories/GHSA-9wv6-86v2-598j

It is triggered because of the following dependencies:

https://github.com/lwsjs/rewrite/blob/b3747c60075e253482639c2c8d9c003865a3ebe1/package.json#L34-L35

So `path-to-regexp` is required directly, and indirectly via `koa-route`.

If possible, please upgrade the two packages in question.

**Comment by apepper** [comment]
Related issues: https://github.com/lwsjs/blacklist/issues/2 and https://github.com/koajs/route/issues/73.

**Comment by 75lb** [comment]
thanks, will look in a few hours time

**Comment by 75lb** [comment]
This will take a toucher longer to fix as upgrading path-to-regexp will break lws-rewrite and lws-blacklist due to [major breaking changes](https://github.com/pillarjs/path-to-regexp/releases/tag/v7.0.0) in path-to-regexp recently.. I will likely drop path-to-regexp entirely and replace its previous behaviour (mainly the support for regexp input expressions, which has since been dropped) with something hand-rolled.

**Comment by 75lb** [comment]
Made [a request](https://github.com/pillarjs/path-to-regexp/issues/326) while I work on a new solution..

**Comment by 75lb** [comment]
the advisory fix has been implemented in [path-to-regexp v6.3.0](https://github.com/pillarjs/path-to-regexp/commits/6.x/).. This was a minor version release, meaning lws-rewrite, lws-blacklist and @koa/router will now pick up the fixed module if you reinstall.

According to https://github.com/koajs/router/issues/186, you may still receive an advisory message but this should clear within a few days once the advisory database is updated.
